### ISSUE TITLE
Please remember to indicate the source of your Figure 1

### ISSUE THREAD

**Issue by HaolingZHANG** [ylu1997/ylu1997.github.io#1]
Hi,

The source of Figure 1 in your [paper](https://ylu1997.github.io/Only3000/dnapdf.pdf) is Figure 1 from [SPIDER-WEB](https://arxiv.org/pdf/2204.02855v1).

Please remember to acknowledge and cite such meticulously crafted figures.

Thanks,
Haoling

**Comment by ylu1997** [comment]
Dear Haoling,

Thank you for bringing to my attention the omission of your citation in the article on my personal website. I sincerely apologize for this oversight and have promptly corrected it to include the proper citation to your work.

I greatly appreciate the impact of your research on my own work and thank you for your understanding and patience. If you have any further suggestions or comments, please do not hesitate to let me know.

Best regards,

Yi

**Comment by HaolingZHANG** [comment]
Thanks
